config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get('/', {to: 'users#show', as: 'root'})

  get('/users/getUserByUserName', to: 'users#getUserByUserName')
  # users controller
  resources :users
  resources :requests, only: [:create, :update]
  # sessions controller
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  resources :chanels do
    resources :messages
    
  end
  get('/messages/getMoreMsg', to: 'messages#getMoreMsg')
  # mount ActionCable.server => '/cable'
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    # relationships
    has_many :chanel_users
    has_many :friend_chanels, ->{ where(is_group: false)} , through: :chanel_users, source: :chanel
    has_many :group_chanels, ->{ where(is_group: true)} , through: :chanel_users, source: :chanel
    has_many :channels, through: :chanel_users, source: :chanel

    # has_many :friends, ->{ where(is_group: false)}, through: :chanel_users, source: :user
    has_many :friends, ->{ where(:user_id != self.id)}, through: :friend_chanels, source: :chanel_users
    # has_many :friends, :class_name => 'User', :finder_sql => '
    #     SELECT users.* FROM users INNER JOIN chanel_users ON chanel_users.user_id = users.id 
    #     WHERE chanel_users.chanel_id in 
    #     (SELECT chanels.id
    #     FROM chanels INNER JOIN chanel_users ON chanel_users.chanel_id = chanels.id 
    #     WHERE chanel_users.user_id = #{id} AND chanels.is_group = false)'
    has_many :received_requests, class_name: "Request", foreign_key: :receiver_id
    has_many :sent_requests, class_name: "Request", foreign_key: :sender_id

    # validations
    validates(:user_name, presence: true, uniqueness: true)
    validates(:email, presence: true, uniqueness: true)

    # before create
    before_create :set_default_picture_url

    

    private

    def set_default_picture_url
        self.picture_url ||= "logo.png"
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :show]
  before_action :find_user, only: [:show, :edit, :update]

    def new
        @user = User.new
      end
      
    def create
      @user = User.new user_params
      if @user.picture_url == ""
        @user.picture_url = "logo.png"
      end
      if @user.save
        session[:user_id] = @user.id
        cookies[:user_id] = @user.id
        redirect_to root_path, notice: "Logged In!"
      else
        render :new
      end
    end

    def show
      @requests_from = Request.select("users.id as user_id, users.user_name, users.picture_url, requests.*").joins("INNER JOIN users ON users.id = requests.sender_id").where("receiver_id = #{current_user.id}")
      @requests_to = Request.select("users.user_name, users.picture_url, requests.*").joins("INNER JOIN users ON users.id = requests.receiver_id").where("sender_id = #{current_user.id}")
      # requests_from + requests_to
      @friends_number = Request.where("(receiver_id = #{current_user.id} OR sender_id = #{current_user.id}) AND is_accepted = true").count
    end
    
    def edit
    
    end

    def update
      if @user.picture_url == ""
        @user.picture_url = "logo.png"
      end
      if @user.update user_params
        redirect_to root_path(@user)
      else
        render :edit
      end
    end
    
    def getUserByUserName
      if params[:user_name]
        user = User.find_by(user_name: params[:user_name])
        if user != nil
          render json: {user: user, status: 200 }
        else
          render json:{ errors: "null" , status: 404}
        end
      else
        render json:{ errors: "null", status: 404 }
      end
    end
    

    private
    
    def user_params
      params.require(:user).permit(:user_name, :email, :password, :password_confirmation, :picture_url,:description)
    end

    def find_user
      @user = current_user
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="signup-and-login-form">
    <h1>Edit info</h1>
    
    <% if @user.errors.any? %>
    <ul>
        <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
    <% end %>
    
    <%= form_for(@user, :html => {:class=>'ui form'}) do |f| %>
    <div class="field">
        <%= f.label :user_name %>
        <%= f.text_field :user_name %>
    </div>
    <div class="field">
        <%= f.label :email %>
        <%= f.email_field :email %>
    </div>
    <div class="field">
        <%= f.label :picture_url %>
        <%= f.text_field :picture_url %>
    </div>
    <div class="field">
        <%= f.label :description %>
        <%= f.text_area :description %>
    </div>
    <%= f.submit "Submit", class:"ui primary button" %>
    <% end %>
</div>

app/views/users/new.html.erb
<div class="signup-and-login-form">
    <h1>Sign Up</h1>
    
    <% if @user.errors.any? %>
    <ul>
        <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
    <% end %>
    
    <%= form_for(@user, :html => {:class=>'ui form'}) do |f| %>
    <div class="field">
        <%= f.label :user_name %>
        <%= f.text_field :user_name %>
    </div>
    <div class="field">
        <%= f.label :email %>
        <%= f.email_field :email %>
    </div>
    <div class="field">
        <%= f.label :picture_url %>
        <%= f.text_field :picture_url %>
    </div>
    <div class="field">
        <%= f.label :password %>
        <%= f.password_field :password %>
    </div>
    <div class="field">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
    </div>
    <div class="field">
        <%= f.label :description %>
        <%= f.text_area :description %>
    </div>
    <%= f.submit "Submit", class:"ui primary button" %>
    <% end %>
</div>

app/views/users/show.html.erb
<div class="show-user">
    <div class="ui negative hidden message">
        <i class="close icon"></i>
        <p></p>
    </div>
    <div class="user-info">
        <div class="ui card">
            <div class="image">
                <%= image_tag(@user.picture_url)%>
            </div>
            <div class="content">
                <%= link_to @user.user_name, edit_user_path(@user), class:"header" %>
                <div class="meta">
                <span class="date">Joined in <%= @user.created_at.year%></span>
                </div>
                <div class="description">
                    <%= @user.description %>
                </div>
            </div>
            <div class="extra content">
                <span class="right floated">
                <i class="toggle on icon"></i>
                    <%= link_to "Logout", sessions_path, method: :delete, data:{confirm: "Are you sure you want to log out"}%>
                </span>
                <span>
                <i class="heart icon"></i>
                <%= pluralize(@friends_number, "Friend") %>
                </span>
                
            </div>
        </div>
        <div class="request-list">
            
            <div class="ui feed">
                <% @requests_from.each do |request|%>
                <div class="event">
                    <div class="label">
                        <%= image_tag(request.picture_url)%>
                    </div>
                    <div class="content">
                        <div class="summary">
                            <span class="ui purple label">
                            <%= request.user_name%>
                            </span> wants to add you as a friend
                            <div class="date">
                            <%= time_ago_in_words(request.created_at) %> Ago
                            </div>
                            
                        </div>
                    </div>
                    <div class="ui buttons" style="margin-right:1rem">
                    <% if request.is_accepted == nil%>
                        <button class="ui basic red button" onclick="changeFriend(false,<%= request.user_id %>,<%= request.id %>)">Decline</button>
                        <div class="or"></div>
                        <button class="ui basic green button" onclick="changeFriend(true,<%= request.user_id %>,<%= request.id %>)">Approve</button>
                    <% elsif  request.is_accepted == true %>
                        <div class="ui purple basic label" style="line-height: 22px;">
                            Approved
                        </div>
                    <% else %>
                        <div class="ui red basic label" style="line-height: 22px;width: 75.5px">Declined</div>
                    <% end %>
                    </div>
                </div>
                <% end %>
                <% @requests_to.each do |request|%>
                <div class="event">
                    <div class="label">
                        <%= image_tag(current_user.picture_url)%>
                    </div>
                    <div class="content">
                        <div class="summary">
                            You sent a friend request to 
                            <span class="ui purple image label" style="margin-top: -13px;">
                                <%= image_tag(request.picture_url)%>
                                <%= request.user_name%>
                            </span>
                            <div class="date">
                            <%= time_ago_in_words(request.created_at) %> Ago
                            </div>
                            
                        </div>
                    </div>
                    <div style="margin-right:1rem">
                    <% if request.is_accepted == nil%>
                        <div class="ui grey basic label" style="line-height: 22px;width: 75.5px;text-align:center">Waiting</div>
                    <% elsif  request.is_accepted == true %>
                        <div class="ui purple basic label" style="line-height: 22px;">
                            Approved
                        </div>
                    <% else %>
                        <div class="ui red basic label" style="line-height: 22px;width: 75.5px">Declined</div>
                    <% end %>
                    </div>
                </div>
                <% end %>
            </div>
        </div>
    </div>
    <div style="display:flex;justify-content:space-between;margin-bottom:10px;align-content:center;">
        <h2>Friend List</h2>
        <button class="ui purple basic button" id="addNewFriendBtn" style="margin-right:10rem">Add New Friend</button>
    </div>
    <div class="ui link cards">
        <% getFriendList.each do |friend| %>
        <div class="card">
            <div class="image">
                <%= image_tag(friend.picture_url)%>
            </div>
            <div class="content">
            <div class="header"><%= friend.user_name%></div>
                <div class="meta">
                    Joined in <%= friend.created_at.year%>
                </div>
                <div class="description">
                    <%= friend.description %>
                </div>
            </div>
        </div>
        <% end %>

    </div>
    <div class="ui modal" id="add_new_friend_modal">
        <i class="close icon"></i>
        <div class="header">
            Add New Friend
        </div>
        <div class="image content" style="min-height: 122px;">
            <div class="user-add-new-friend">
                <img style="display:none;width: 80px;height: 80px;">
                <span style="display:none;line-height:80px">Nope~</span>
            </div>
            <div class="description ui form">
                <div class="field">
                    <label>User Name</label>
                    <input type="text" style="width:70%" id="user_name" name="user_name" placeholder="Please input the user name">
                    <input type="hidden" id="receiver_id" value="">
                    <button class="ui primary basic button" style="margin-left:2rem;" id="searchBtn">Search</button>
                </div>
            </div>
        </div>
        <div class="actions">
            <button disabled="false" class="ui positive right labeled icon button" id="sendRequestBtn">
                Send the request!
                <i class="checkmark icon"></i>
            </button>
        </div>
    </div>
</div>
<script>
function changeFriend(is_accepted, sender_id, request_id) {
    $.ajax({
        type: "PATCH",
        url: `/requests/${request_id}`,
        data: { sender_id, is_accepted },
        dataType: "json",
        success: function (data) {
            window.location = window.location;
        }
    });
}
</script>